### ISSUE TITLE
App crashes when running collect_data

### ISSUE THREAD

**Issue by forsgren** [trevorprater/wholikes#1]
This is the printout in the terminal:

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bottle-0.12.9-py2.7.egg/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Library/Python/2.7/site-packages/bottle-0.12.9-py2.7.egg/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "app.py", line 96, in collect_data
    token = request.session['access_token']
  File "/Library/Python/2.7/site-packages/Beaker-1.7.0-py2.7.egg/beaker/session.py", line 672, in __getitem__
    return self._session()[key]
KeyError: 'access_token'
127.0.0.1 - - [26/Dec/2015 22:02:11] "GET /collect_data HTTP/1.1" 500 753
```

**Comment by trevorprater** [comment]
It is likely that you are still using my client-secret. I did not intend to share this publicly, so I was forced to reset the value. If you generate a new client-key and client-secret via instagram, the app is likely to work.

**Comment by forsgren** [comment]
I've generated new client-key and client-secret (created my own Instagram app through their dev pages), and added them to the code (both in app.py and wholikes.py). Still getting the same error.

**Comment by forsgren** [comment]
Just noticed I'm getting a "[Errno 13] Permission denied" when I click "Connect with Instagram". Any particular permissions that has to be set up?

**Comment by forsgren** [comment]
Here's a bit more precise description on what's happening for me 

**Action:** Making a request to http://localhost:8515/
**Output in terminal:**

```
127.0.0.1 - - [27/Dec/2015 11:14:51] "GET / HTTP/1.1" 200 221
```

**Action:** Clicking "Connect with Instagram"
**Output in terminal:**

```
[Errno 13] Permission denied
127.0.0.1 - - [27/Dec/2015 11:14:56] "GET /oauth_callback?code=[code_manually_removed] HTTP/1.1" 200 78
```

**Action:** Clicking "Collect Data"
**Output in terminal:**

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bottle-0.12.9-py2.7.egg/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Library/Python/2.7/site-packages/bottle-0.12.9-py2.7.egg/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "app.py", line 96, in collect_data
    token = request.session['access_token']
  File "/Library/Python/2.7/site-packages/Beaker-1.7.0-py2.7.egg/beaker/session.py", line 672, in __getitem__
    return self._session()[key]
KeyError: 'access_token'
```

Update 2015-12-27 11:37:
It seems as if it's the line

```
access_token, user_info = unauthenticated_api.exchange_code_for_access_token(code)
```

that triggers the "[Errno 13] Permission denied" message
